fix bug

diff --git a/addons/nacos/nacos-server-initdb-v2.2.3/entrypoint b/addons/nacos/nacos-server-initdb-v2.2.3/entrypoint
--- a/addons/nacos/nacos-server-initdb-v2.2.3/entrypoint
+++ b/addons/nacos/nacos-server-initdb-v2.2.3/entrypoint
@@ -7,35 +7,35 @@ MYSQL_PORT=${MYSQL_PORT:-3306}
 MYSQL_USER=$MYSQL_USER
 MYSQL_PASSWD=$MYSQL_PASSWD
 MYSQL_DB=$MYSQL_DB
-SQL_FILES=$BASE_DIR/conf/mysql-schema.sql
+SQL_FILE=$BASE_DIR/conf/mysql-schema.sql
 
 function log() {
-    echo "$@"
+  echo "$@"
 }
 
 # check mysql connection
 function check_conn() {
-    mysql -h$MYSQL_HOST -u$MYSQL_USER -p$MYSQL_PASSWD -P$MYSQL_PORT $MYSQL_DB -e "select 1;" > /dev/null
-    return $?
+  mysql -h$MYSQL_HOST -u$MYSQL_USER -p$MYSQL_PASSWD -P$MYSQL_PORT $MYSQL_DB -e "select 1;" >/dev/null
+  return $?
 }
 
 # exec sql files
-function exec_sql_file() {
-    mysql -h$MYSQL_HOST -u$MYSQL_USER -p$MYSQL_PASSWD -P$MYSQL_PORT $MYSQL_DB < $SQL_FILES > /dev/null 2>&1 \
-
-}
 
 check_conn
 if [ $? -ne 0 ]; then
-    log "Mysql connect error."
-    exit 10
+  log "Mysql connect error."
+  exit 10
 fi
 
-if [ ! -f "$SQL_FILES" ]; then
-    log "$SQL_FILES not found."
-    exit 20
+if [ ! -f "$SQL_FILE" ]; then
+  log "$SQL_FILE not found."
+  exit 20
 fi
 
-exec_sql_file
+# exec sql file
+mysql -h$MYSQL_HOST -u$MYSQL_USER -p$MYSQL_PASSWD -P$MYSQL_PORT $MYSQL_DB <$SQL_FILE >/dev/null || {
+  log "exec sql file failed."
+  exit 30
+}
 
 log "Used $SECONDS seconds."
