update

diff --git a/addons/nacos/nacos-server-initdb-v2.2.3/entrypoint b/addons/nacos/nacos-server-initdb-v2.2.3/entrypoint
--- a/addons/nacos/nacos-server-initdb-v2.2.3/entrypoint
+++ b/addons/nacos/nacos-server-initdb-v2.2.3/entrypoint
@@ -15,7 +15,7 @@ function log() {
 
 # check mysql connection
 function check_conn() {
-  mysql -h$MYSQL_HOST -u$MYSQL_USER -p$MYSQL_PASSWD -P$MYSQL_PORT $MYSQL_DB -e "select 1;" >/dev/null
+  mysql -h"${MYSQL_HOST}" -u"${MYSQL_USER}" -p"${MYSQL_PASSWD}" -P"${MYSQL_PORT}" "${MYSQL_DB}" -e "select 1;" >/dev/null
   return $?
 }
 
@@ -32,8 +32,14 @@ if [ ! -f "$SQL_FILE" ]; then
   exit 20
 fi
 
+# create database
+mysql -h"${MYSQL_HOST}" -u"${MYSQL_USER}" -p"${MYSQL_PASSWD}" -P"${MYSQL_PORT}" -e "CREATE DATABASE IF NOT EXISTS nacos" >/dev/null || {
+  log "exec sql file failed."
+  exit 30
+}
+
 # exec sql file
-mysql -h$MYSQL_HOST -u$MYSQL_USER -p$MYSQL_PASSWD -P$MYSQL_PORT $MYSQL_DB <$SQL_FILE >/dev/null || {
+mysql -h"${MYSQL_HOST}" -u"${MYSQL_USER}" -p"${MYSQL_PASSWD}" -P"${MYSQL_PORT}" "${MYSQL_DB}" <"${SQL_FILE}" >/dev/null || {
   log "exec sql file failed."
   exit 30
 }
